
# DROP TABLE T_THERAFLU_MAP;

CREATE TABLE T_THERAFLU_MAP (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CITY VARCHAR(100) NOT NULL,
	DT DATE NOT NULL,
	IDX INTEGER NOT NULL
);

ALTER TABLE T_THERAFLU_MAP ADD UNIQUE T_THERAFLU_MAP_IDX(CITY, DT);


INSERT INTO T_SERVICE (NAME, NOTE, IS_ACTIVE, IS_AUTO_EMAIL_NOTIFY) VALUES ('TheraFlu Map', '', 1, 0);